src/main/java/br/com/petshop/model/Cachorro.java
package br.com.petshop.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Cachorro extends EntidadeDominio implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	private Integer id;
	private String nome;
	private Integer idade;
	private String raca;
	private String pathImagem;
	private String endereco;
	private String observacao;
	
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdade() {
		return idade;
	}

	public void setIdade(Integer idade) {
		this.idade = idade;
	}

	public String getRaca() {
		return raca;
	}

	public void setRaca(String raca) {
		this.raca = raca;
	}

	public String getPathImagem() {
		return pathImagem;
	}

	public void setPathImagem(String pathImagem) {
		this.pathImagem = pathImagem;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}
	
}

src/main/java/br/com/petshop/model/Cliente.java
package br.com.petshop.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.petshop.model.Cachorro;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
@Entity
public class Cliente extends EntidadeDominio implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	private Integer id;

	private String nome;
	private String telefone;
	
	@OneToMany(fetch=FetchType.EAGER)
	private List<Cachorro> cachorros = new ArrayList<Cachorro>();
	
	@ManyToMany(fetch=FetchType.EAGER)
	@Fetch(FetchMode.SUBSELECT)
	private List<Servico> servicos = new ArrayList<Servico>();
	
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar dataCadastro = Calendar.getInstance();
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public List<Cachorro> getCachorros() {
		return cachorros;
	}

	public void setCachorros(List<Cachorro> cachorros) {
		this.cachorros = cachorros;
	}
	
	public void adicionaCachorro(Cachorro cachorro) {
		this.cachorros.add(cachorro);
	}
	
	public void removeCachorro(Cachorro cachorro) {
		this.cachorros.remove(cachorro);
	}

	public List<Servico> getServicos() {
		return servicos;
	}

	public void setServicos(List<Servico> servicos) {
		this.servicos = servicos;
	}
	
	public void adicionaServico(Servico servico) {
		this.servicos.add(servico);
	}
	
	public void removeServico(Servico servico) {
		this.servicos.remove(servico);
	}

	public Calendar getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(Calendar dataCadastro) {
		this.dataCadastro = dataCadastro;
	}
	
}

src/main/java/br/com/petshop/model/EntidadeDominio.java
package br.com.petshop.model;

public class EntidadeDominio {

}

src/main/java/br/com/petshop/model/Servico.java
package br.com.petshop.model;

import java.io.Serializable;
import java.util.Calendar;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Servico extends EntidadeDominio implements Serializable{
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	private Integer id;
	private String nome;
	private double preco;
	private String descricao;
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar dataServico = Calendar.getInstance();
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public double getPreco() {
		return preco;
	}
	public void setPreco(double preco) {
		this.preco = preco;
	}
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	public Calendar getDataServico() {
		return dataServico;
	}
	public void setDataServico(Calendar dataServico) {
		this.dataServico = dataServico;
	}
	
}

src/main/java/br/com/petshop/model/Usuario.java
package br.com.petshop.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Usuario implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	@Id
    @GeneratedValue
    private Integer id;
    private String email;
    private String senha;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
	
	
}

src/main/java/br/com/petshop/mb/TemaMB.java
package br.com.petshop.mb;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class TemaMB implements Serializable{

	private static final long serialVersionUID = 1L;
	
	private String tema = "bluesky";

	public String getTema() {
		return tema;
	}

	public void setTema(String tema) {
		this.tema = tema;
	}
	
	public String[] getTemas() {
	    return new String[] { "afterdark", "afternoon", "afterwork", "aristo",
	            "black-tie", "blitzer", "bluesky", "bootstrap", "casablanca",
	            "cupertino", "cruze", "dark-hive", "delta", "dot-luv",
	            "eggplant", "excite-bike", "flick", "glass-x", "home",
	            "hot-sneaks", "humanity", "le-frog", "midnight", "mint-choc",
	            "overcast", "pepper-grinder", "redmond", "rocket", "sam",
	            "smoothness", "south-street", "start", "sunny", "swanky-purse",
	            "trontastic", "ui-darkness", "ui-lightness", "vader" };
	}
}

src/main/java/br/com/petshop/mb/UsuarioMB.java
package br.com.petshop.mb;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.petshop.TX.Transacional;
import br.com.petshop.facade.UsuarioFacade;
import br.com.petshop.model.Usuario;
import br.com.petshop.util.RedirectView;

@Named
@ViewScoped
public class UsuarioMB implements Serializable{

	private static final long serialVersionUID = 1L;

	private Usuario usuario = new Usuario();

	private Integer usuarioId;

	@Inject
	private UsuarioFacade usuarioFacade;
	
	public UsuarioMB() {
		
	}
		
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Transacional
	public RedirectView gravar() {		
		System.out.println("Gravando usuario " + this.usuario.getEmail());		
		if (this.usuario.getId() == null) {
			usuarioFacade.save(this.usuario);
		}
		else {
			usuarioFacade.update(this.usuario);
		}
		this.usuario = new Usuario();		
		return new RedirectView("usuario");
	}
	
	public List<Usuario> getUsuarios() {
		return usuarioFacade.selectAll();
	}
	
	@Transacional
	public void remover(Usuario usuario) {
		System.out.println("Removendo usuario " + usuario.getEmail());
		usuarioFacade.delete(usuario);
	}
	
	public void carregar(Usuario usuario) {
		 System.out.println("Carregando usuario " + usuario.getEmail());
		 this.usuario = usuario;
	}
	
	public void carregarCachorroPeloId() {
		this.usuario = usuarioFacade.selectById(usuarioId);
		if(this.usuario == null) {
			this.usuario = new Usuario();
		}
	} 
}

src/main/webapp/_template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:fn="http://java.sun.com/jsp/jstl/functions">
	
	<h:head/>
    
    <h:body>
        <div id="cabecalho">
            <h:graphicImage library="img" name="cachorro.png"/>
            <h1><ui:insert name="titulo"></ui:insert></h1>
        </div>
        
		<h:panelGrid columns="2">
			<h:form rendered="#{usuarioLogado != null}" >
    			<p:themeSwitcher id="escolherTema" style="width:165px" value="#{temaMB.tema}">
        			<f:selectItem itemLabel="Escolher tema" itemValue="" />
        			<f:selectItems value="#{temaMB.temas}" var="tema" itemLabel="#{tema}" itemValue="#{tema}" />
    				<f:ajax />
    			</p:themeSwitcher>
			</h:form>
		</h:panelGrid>
		
        <p:growl id="growl" showDetail="true" autoUpdate="true" sticky="true"/>
        
        <h:form id="formMenu" rendered="#{usuarioLogado != null}">     
	        <p:menubar>
	   			<p:submenu label="Cadastros" icon="ui-icon-document">
	            	<p:menuitem value="Clientes" action="cliente?faces-redirect=true"  icon="fa fa-fw fa-edit" />
	                <p:separator />
	            	<p:menuitem value="Cachorro" action="cachorro?faces-redirect=true"  icon="fa fa-fw fa-edit"/>
	            	<p:separator />
	            	<p:menuitem value="Serviços" action="servicos?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	            	
			    </p:submenu>
				
				<p:submenu label="Gerenciar Serviços" icon="ui-icon-document">	            	
	            	<p:menuitem value="Cadastrar Serviços" action="servicos?faces-redirect=true"  icon="fa fa-fw fa-edit"/>
	            	<p:menuitem value="Atribuir à clientes" action="servicoCliente?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	 	            	
			     </p:submenu>

     			<p:submenu label="Relatórios">
     				<p:menuitem value="Serviços por cliente" action="servicosPorCliente?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	
        			<p:menuitem value="Serviços por mês" action="servicosPorMes?faces-redirect=true" icon="fa fa-fw fa-edit"/>		
    			</p:submenu>
    			
    			<p:submenu label="Outros">
     				<p:menuitem value="Gerenciar Usuários" action="usuario?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	
        			<p:menuitem value="Logout" action="#{loginBean.deslogar}" icon="fa fa-fw fa-sign-out"/>		
    			</p:submenu>
			</p:menubar>
        </h:form>
        
        
        
        <div id="conteudo">
            <ui:insert name="conteudo">
            </ui:insert>
        </div>      
    </h:body>
</html>

src/main/webapp/cachorro.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Novo Cachorro</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">
         
        
        <h:messages globalOnly="true" />
            
        <h:form enctype="multipart/form-data" id="cachorro">
                <p:fieldset legend="Dados do Cachorro">
                    <h:panelGrid columns="2">
				
					<p:outputLabel value="Nome:" for="nome" />
					<p:inputText id="nome" value="#{cachorroMB.cachorro.nome}"
						required="true">
						<f:validateLength minimum="2" />
					</p:inputText>

					<p:outputLabel value="Idade:" for="idade" />
					<p:inputText id="idade" value="#{cachorroMB.cachorro.idade}"
						required="true">
						<f:validateLength minimum="1" />
					</p:inputText>
					
					<p:outputLabel value="Raça:" for="raca" />
					<p:inputText id="raca" value="#{cachorroMB.cachorro.raca}"
						required="true">
						<f:validateLength minimum="3" />
					</p:inputText>
					
					<p:outputLabel value="Endereço:" for="endereco" />
					<p:inputText id="endereco" value="#{cachorroMB.cachorro.endereco}"
						required="true">
						<f:validateLength minimum="3" />
					</p:inputText>
					
					<p:outputLabel value="Observação:" for="observacao" />
					<p:inputText id="observacao" value="#{cachorroMB.cachorro.observacao}"
						required="true">
						<f:validateLength minimum="3" />
					</p:inputText>
								
					<p:outputLabel value="Foto do Cachorrro" />
    				<h:inputFile value="#{cachorroMB.fotoCachorro}" id="fotoCachorro" />
    	    											
				  </h:panelGrid>
				<p:commandButton value="Gravar" action="#{cachorroMB.gravar}" process="@form" update="@form formTabelaCachorros" ajax="false" />
			</p:fieldset>    
		</h:form>
		
		<h:form id="formTabelaCachorros">
		  <p:dataTable var="cachorro" value="#{cachorroMB.cachorros}" rows="10" paginator="true">
                    <f:facet name="header">
                    	Lista de Cachorros Cadastrados
                    </f:facet>
                    <p:column headerText="Nome" sortBy="#{cachorro.nome}"
                           filterBy="#{cachorro.nome}">
                           <a href="#{request.contextPath}/detalhesCachorro.xhtml?id=#{cachorro.id}" title="#{cachorro.nome}">
                           
                           <h:outputText value="#{cachorro.nome}" />
                           </a>
                    </p:column>
  
  					<p:column headerText="Raça" sortBy="#{cachorro.raca}"
                           filterBy="#{cachorro.raca}">
                           <h:outputText value="#{cachorro.raca}" />
                    </p:column>
  
                    <p:column headerText="Idade" sortBy="#{cachorro.idade}"
                           filterBy="#{cachorro.idade}">
                           <h:outputText value="#{cachorro.idade} ano(s)"/>
                    </p:column>
                      
                    <p:column headerText="Endereco" sortBy="#{cachorro.endereco}"
                           filterBy="#{cachorro.endereco}">
                           <h:outputText value="#{cachorro.endereco}"/>
                    </p:column>
                    
                    <p:column headerText="Observações" sortBy="#{cachorro.observacao}"
                           filterBy="#{cachorro.idade}">
                           <h:outputText value="#{cachorro.observacao}"/>
                    </p:column>  
                      
                    <p:column headerText="Foto do Cachorro">
                    	<h:graphicImage library="img" name="#{cachorro.pathImagem}"/>
                    </p:column>
                      
                    <!-- Alterar  -->
                    <p:column headerText="Alterar" >
                     	<p:commandButton icon="fa fa-fw fa-edit" value="Alterar" update=":cachorro">
            				<f:setPropertyActionListener value="#{cachorro}" target="#{cachorroMB.cachorro}" />
        				</p:commandButton>
                    </p:column>
                    <!-- Remover -->
                     <p:column headerText="Remover" >
                           <p:commandButton icon="fa fa-fw fa-remove" value="Remover" action="#{cachorroMB.remover(cachorro)}" update="@form" />
                    </p:column>
  					<f:facet name="footer">
                     	<h:outputText value="Existem " />
                     	<h:outputText value="#{fn:length(cachorroMB.cachorros)}" />
                    	<h:outputText value=" cachorros cadastrados. " />
	                </f:facet>
             </p:dataTable>
		</h:form>
	
	
	</ui:define>
</ui:composition>

</html>

src/main/webapp/detalhesCachorro.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<f:metadata>
	    <f:viewParam value="#{cachorroMB.cachorroId}" name="id" />
	    <f:viewAction action="#{cachorroMB.carregarDetalhe()}" />
	</f:metadata>

<ui:composition template="_template.xhtml">

	<ui:define name="nome">
		<p:outputPanel>#{cachorroMB.cachorro.nome}</p:outputPanel>
	</ui:define>

	<ui:define name="conteudo">


		<h:messages globalOnly="true" />

		<h:form>
			<p:dataTable>
			
				<p:column headerText="Nome">
					<h:outputText value="#{cachorroMB.cachorro.nome}" />
				</p:column>

				<p:column headerText="raca">
					<h:outputText value="#{cachorroMB.cachorro.raca}" />
				</p:column>

				<p:column headerText="endereco">
					<h:outputText value="#{cachorroMB.cachorro.endereco}" />
				</p:column>

				<p:column headerText="observacao">
					<h:outputText value="#{cachorroMB.cachorro.observacao}" />
				</p:column>

				<p:column headerText="Foto">
					<p:graphicImage value="#{cachorroMB.cachorro.pathImagem}" />
				</p:column>
			</p:dataTable>

		</h:form>
	</ui:define>
</ui:composition>

</html>

src/main/webapp/detalhesCliente.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">



	<ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Detalhes do Cliente</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">
         
        
        <h:messages globalOnly="true" />
        
        
        
               		
		<h:form id="formTabelaCachorros">
		  <p:dataTable var="cachorro" value="#{cachorroMB.cachorros}" rows="10">
                    <f:facet name="header">
                    	Lista de Cachorros Cadastrados
                    </f:facet>
                    <p:column headerText="Nome" sortBy="#{cachorro.nome}"
                           filterBy="#{cachorro.nome}">
                           <h:outputText value="#{cachorro.nome}" />
                    </p:column>
  
  					<p:column headerText="Raça" sortBy="#{cachorro.raca}"
                           filterBy="#{cachorro.raca}">
                           <h:outputText value="#{cachorro.raca}" />
                    </p:column>
  
                    <p:column headerText="Idade" sortBy="#{cachorro.idade}"
                           filterBy="#{cachorro.idade}">
                           <h:outputText value="#{cachorro.idade} ano(s)"/>
                    </p:column>
                      
                    <!-- Alterar  -->
                    <p:column headerText="Alterar" >
                     	<p:commandButton icon="fa fa-fw fa-edit" value="Alterar" update=":cachorro">
            				<f:setPropertyActionListener value="#{cachorro}" target="#{cachorroMB.cachorro}" />
        				</p:commandButton>
                    </p:column>
                    <!-- Remover -->
                     <p:column headerText="Remover" >
                           <p:commandButton icon="fa fa-fw fa-remove" value="Remover" action="#{cachorroMB.remover(cachorro)}" update="@form" />
                    </p:column>
  					<f:facet name="footer">
                     	<h:outputText value="Existem " />
                     	<h:outputText value="#{fn:length(cachorroMB.cachorros)}" />
                    	<h:outputText value=" cachorros cadastrados. " />
	                </f:facet>
             </p:dataTable>
		</h:form>
	
	
	</ui:define>
</ui:composition>

</html>

src/main/webapp/estilo.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Escolher estilo das páginas</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">
         
        	<h:messages globalOnly="true" />
            
      		<h:panelGrid columns="2">
				<h:form rendered="#{usuarioLogado != null}" >
	    			<p:themeSwitcher id="escolherTema" style="width:165px" value="#{temaMB.tema}">
	        			<f:selectItem itemLabel="Escolher tema" itemValue="" />
	        			<f:selectItems value="#{temaMB.temas}" var="tema" itemLabel="#{tema}" itemValue="#{tema}" />
	    				<f:ajax />
	    			</p:themeSwitcher>
				</h:form>
			</h:panelGrid>
		
		</ui:define>
	</ui:composition>

</html>

src/main/webapp/servicosPorCliente.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">



	<ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Relatório - Serviços por cliente</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">

        	<h:messages globalOnly="true" />
            
      	</ui:define>
      	
	</ui:composition>

</html>

src/main/webapp/usuario.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">



	<ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Novo Usuário</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">
         
        
        <h:messages globalOnly="true" />
            
        <h:form id="usuario">
                <p:fieldset legend="Dados do Usuário">
                    <h:panelGrid columns="2">
				
					<p:outputLabel value="Email:" for="email" />
					<p:inputText id="email" value="#{usuarioMB.usuario.email}"
						required="true">
						<f:validateLength minimum="2" />
					</p:inputText>

					<p:outputLabel value="Senha:" for="senha" />
					<p:password id="senha" value="#{usuarioMB.usuario.senha}"	required="true"/>
					
				  </h:panelGrid>
				<p:commandButton value="Gravar" action="#{usuarioMB.gravar}" process="@form" update="@form formTabelaUsuarios" />
			</p:fieldset>    
		</h:form>
		
		<h:form id="formTabelaUsuarios">
		  <p:dataTable var="usuario" value="#{usuarioMB.usuarios}" rows="10">
                    <f:facet name="header">
                    	Lista de Usuários Cadastrados
                    </f:facet>
                    <p:column headerText="Email" sortBy="#{usuario.email}"
                           filterBy="#{usuario.email}">
                           <h:outputText value="#{usuario.email}" />
                    </p:column>
                        
                    <!-- Alterar  -->
                    <p:column headerText="Alterar" >
                     	<p:commandButton icon="fa fa-fw fa-edit" value="Alterar" update=":usuario">
            				<f:setPropertyActionListener value="#{usuario}" target="#{usuarioMB.usuario}" />
        				</p:commandButton>
                    </p:column>
                    <!-- Remover -->
                     <p:column headerText="Remover" >
                           <p:commandButton icon="fa fa-fw fa-remove" value="Remover" action="#{usuarioMB.remover(usuario)}" update="@form" />
                    </p:column>
  					<f:facet name="footer">
                     	<h:outputText value="Existem " />
                     	<h:outputText value="#{fn:length(usuarioMB.usuarios)}" />
                    	<h:outputText value=" usuarios cadastrados. " />
	                </f:facet>
             </p:dataTable>
		</h:form>
	
	
	</ui:define>
</ui:composition>

</html>